AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MahjongScoreLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: build/index.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          NODE_ENV: production
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints: ['src/index.ts']
